using BookTracker.Data;
using BookTracker.Data.Models;
using BookTracker.Web.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace BookTracker.Web.Services;

// One-shot startup task that re-derives Book.Genres from the upstream
// metadata using the (now-tighter) FuzzyGenreMatch + denylist. Existing
// genre assignments on each book are CLEARED before re-applying — Drew
// signed off on this since at backfill time the existing data was
// generated by the buggy matcher (Christie books mis-tagged as Science
// Fiction / Romance).
//
// Idempotent via a MaintenanceLog marker, same pattern as
// EditionFormatBackfillService.
public class BookGenreBackfillService(
    IDbContextFactory<BookTrackerDbContext> dbFactory,
    IBookLookupService lookup,
    ILogger<BookGenreBackfillService> logger) : BackgroundService
{
    private const string MarkerName = "BackfillBookGenres-v1";

    // Polite delay between Open Library calls. Settable so unit tests can
    // skip the wait; production never overrides it.
    public TimeSpan ApiThrottle { get; init; } = TimeSpan.FromMilliseconds(200);

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        try
        {
            await RunBackfillAsync(stoppingToken);
        }
        catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested)
        {
            // Shutdown — leave marker absent so it retries on next start.
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Book genre backfill failed unexpectedly");
        }
    }

    public async Task RunBackfillAsync(CancellationToken ct)
    {
        await using (var probe = await dbFactory.CreateDbContextAsync(ct))
        {
            if (await probe.MaintenanceLogs.AnyAsync(m => m.Name == MarkerName, ct))
            {
                logger.LogDebug("Book genre backfill already completed; skipping");
                return;
            }
        }

        logger.LogInformation("Starting book genre backfill");

        await using var db = await dbFactory.CreateDbContextAsync(ct);
        var books = await db.Books
            .Include(b => b.Genres)
            .Include(b => b.Editions)
            .Include(b => b.Works).ThenInclude(w => w.Genres)
            .ToListAsync(ct);
        var allGenres = await db.Genres.ToListAsync(ct);

        var updated = 0;
        var skipped = 0;
        var failures = 0;

        foreach (var book in books)
        {
            ct.ThrowIfCancellationRequested();

            var isbn = book.Editions.FirstOrDefault()?.Isbn;
            if (string.IsNullOrWhiteSpace(isbn))
            {
                skipped++;
                continue;
            }

            try
            {
                var result = await lookup.LookupByIsbnAsync(isbn, ct);
                if (result is null)
                {
                    skipped++;
                    continue;
                }

                book.Genres.Clear();
                ApplyMatchedGenres(book, result.GenreCandidates, allGenres);
                WorkSync.EnsureWork(book);
                updated++;
            }
            catch (Exception ex)
            {
                failures++;
                logger.LogWarning(ex, "Backfill genre lookup failed for ISBN {Isbn}", isbn);
            }

            try
            {
                await Task.Delay(ApiThrottle, ct);
            }
            catch (OperationCanceledException) { throw; }
        }

        await db.SaveChangesAsync(ct);

        db.MaintenanceLogs.Add(new MaintenanceLog
        {
            Name = MarkerName,
            CompletedAt = DateTime.UtcNow,
            Notes = $"Reclassified {updated} of {books.Count} books; {skipped} skipped (no ISBN / no lookup); {failures} lookup failures."
        });
        await db.SaveChangesAsync(ct);

        logger.LogInformation(
            "Book genre backfill complete: reclassified {Updated}/{Total}, {Skipped} skipped, {Failures} failures",
            updated, books.Count, skipped, failures);
    }

    // Mirrors the matching used in BulkAddViewModel.SaveBookAsync so the
    // backfill produces the same end state as a fresh bulk-add would.
    private static void ApplyMatchedGenres(Book book, IReadOnlyList<string> candidates, List<Genre> allGenres)
    {
        if (candidates.Count == 0) return;

        var matched = new HashSet<int>();
        foreach (var candidate in candidates)
        {
            var genre = allGenres.FirstOrDefault(g => GenrePickerViewModel.FuzzyGenreMatch(candidate, g.Name));
            if (genre is not null && matched.Add(genre.Id))
            {
                book.Genres.Add(genre);
                if (genre.ParentGenreId is int parentId && matched.Add(parentId))
                {
                    var parent = allGenres.FirstOrDefault(g => g.Id == parentId);
                    if (parent is not null) book.Genres.Add(parent);
                }
            }
        }
    }
}
